# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
  gen:
    dao:
      - link: "mysql:root:123456@tcp(localhost:3306)/eshop_db?charset=utf8mb4&parseTime=True&loc=Local"
        tables: "sp_brands,sp_categories,sp_category_brands"
        removePrefix: "sp_"
        jsonCase: "Snake"
        jsonOmitEmpty: true
        descriptionTag: true
        noModelComment: true
      - link: "mysql:root:123456@tcp(localhost:3306)/eshop_db?charset=utf8mb4&parseTime=True&loc=Local"
        tables: "sys_staff"
        removePrefix: "sys_"
        jsonCase: "Snake"
        jsonOmitEmpty: true
        descriptionTag: true
        noModelComment: true
