# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
  gen:
    dao:
      - link: "mysql:root:123456@tcp(localhost:3306)/eshop_db?charset=utf8mb4&parseTime=True&loc=Local"
        tables: "sp_brands,sp_categories,sp_category_brands,sp_products,sp_skus,sp_attributes,sp_product_attributes,sp_product_descriptions,sp_product_versions,sp_inventories,sp_inventory_logs,sp_warehouses"
        removePrefix: "sp_"
        jsonCase: "Snake"
        jsonOmitEmpty: true
        descriptionTag: true
        noModelComment: true
      - link: "mysql:root:123456@tcp(localhost:3306)/eshop_db?charset=utf8mb4&parseTime=True&loc=Local"
        tables: "sys_staff,sys_permissions,sys_roles,sys_role_permissions,sys_staff_roles"
        removePrefix: "sys_"
        jsonCase: "Snake"
        jsonOmitEmpty: true
        descriptionTag: true
        noModelComment: true
      - link: "mysql:root:123456@tcp(localhost:3306)/eshop_db?charset=utf8mb4&parseTime=True&loc=Local"
        tables: "sys_login_histories"
        removePrefix: "sys_"
        prefix: "Sys_"
        jsonCase: "Snake"
        jsonOmitEmpty: true
        descriptionTag: true
        noModelComment: true
      - link: "mysql:root:123456@tcp(localhost:3306)/eshop_db?charset=utf8mb4&parseTime=True&loc=Local"
        tables: "usr_login_histories"
        removePrefix: "usr_"
        prefix: "Usr_"
        jsonCase: "Snake"
        jsonOmitEmpty: true
        descriptionTag: true
        noModelComment: true
      - link: "mysql:root:123456@tcp(localhost:3306)/eshop_db?charset=utf8mb4&parseTime=True&loc=Local"
        tables: "base_notifications,base_notification_templates,base_notification_reads"
        removePrefix: "base_"
        jsonCase: "Snake"
        jsonOmitEmpty: true
        descriptionTag: true
        noModelComment: true
      - link: "mysql:root:123456@tcp(localhost:3306)/eshop_db?charset=utf8mb4&parseTime=True&loc=Local"
        tables: "tx_orders,tx_sub_orders,tx_order_logs,tx_order_items,tx_payments,tx_payment_logs,tx_refunds,tx_carts,tx_cart_items"
        removePrefix: "tx_"
        jsonCase: "Snake"
        jsonOmitEmpty: true
        descriptionTag: true
        noModelComment: true
      - link: "mysql:root:123456@tcp(localhost:3306)/eshop_db?charset=utf8mb4&parseTime=True&loc=Local"
        tables: "usr_users,usr_infos,usr_addresses,usr_levels,usr_points,usr_points_rules"
        removePrefix: "usr_"
        jsonCase: "Snake"
        jsonOmitEmpty: true
        descriptionTag: true
        noModelComment: true
      - link: "mysql:root:123456@tcp(localhost:3306)/eshop_db?charset=utf8mb4&parseTime=True&loc=Local"
        tables: "mkt_promotions,mkt_promotion_rules,mkt_promotion_products,mkt_user_promotions,mkt_promotion_usage_logs"
        removePrefix: "mkt_"
        jsonCase: "Snake"
        jsonOmitEmpty: true
        descriptionTag: true
        noModelComment: true
