// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package service

import (
	"context"

	"gf-eshop/api/brands/v1"
)

type IBrands interface {
	List(ctx context.Context, req *v1.ListReq) (res *v1.ListRes, err error)
	Detail(ctx context.Context, req *v1.DetailReq) (res *v1.DetailRes, err error)
	Create(ctx context.Context, req *v1.CreateReq) (res *v1.CreateRes, err error)
	Update(ctx context.Context, req *v1.UpdateReq) (res *v1.UpdateRes, err error)
	Delete(ctx context.Context, req *v1.DeleteReq) (res *v1.DeleteRes, err error)
}

var localBrands IBrands

func Brands() IBrands {
	if localBrands == nil {
		panic("implement not found for interface IBrands, forgot register?")
	}
	return localBrands
}

func RegisterBrands(i IBrands) {
	localBrands = i
}
