// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalAddressesDao is internal type for wrapping internal DAO implements.
type internalAddressesDao = *internal.AddressesDao

// addressesDao is the data access object for table usr_addresses.
// You can define custom methods on it to extend its functionality as you wish.
type addressesDao struct {
	internalAddressesDao
}

var (
	// Addresses is globally public accessible object for table usr_addresses operations.
	Addresses = addressesDao{
		internal.NewAddressesDao(),
	}
)

// Fill with you ideas below.
