// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalAfterSalesDao is internal type for wrapping internal DAO implements.
type internalAfterSalesDao = *internal.AfterSalesDao

// afterSalesDao is the data access object for table tx_after_sales.
// You can define custom methods on it to extend its functionality as you wish.
type afterSalesDao struct {
	internalAfterSalesDao
}

var (
	// AfterSales is globally public accessible object for table tx_after_sales operations.
	AfterSales = afterSalesDao{
		internal.NewAfterSalesDao(),
	}
)

// Fill with you ideas below.
