// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalAfterSaleEvidencesDao is internal type for wrapping internal DAO implements.
type internalAfterSaleEvidencesDao = *internal.AfterSaleEvidencesDao

// afterSaleEvidencesDao is the data access object for table tx_after_sale_evidences.
// You can define custom methods on it to extend its functionality as you wish.
type afterSaleEvidencesDao struct {
	internalAfterSaleEvidencesDao
}

var (
	// AfterSaleEvidences is globally public accessible object for table tx_after_sale_evidences operations.
	AfterSaleEvidences = afterSaleEvidencesDao{
		internal.NewAfterSaleEvidencesDao(),
	}
)

// Fill with you ideas below.
