// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalAfterSaleLogsDao is internal type for wrapping internal DAO implements.
type internalAfterSaleLogsDao = *internal.AfterSaleLogsDao

// afterSaleLogsDao is the data access object for table tx_after_sale_logs.
// You can define custom methods on it to extend its functionality as you wish.
type afterSaleLogsDao struct {
	internalAfterSaleLogsDao
}

var (
	// AfterSaleLogs is globally public accessible object for table tx_after_sale_logs operations.
	AfterSaleLogs = afterSaleLogsDao{
		internal.NewAfterSaleLogsDao(),
	}
)

// Fill with you ideas below.
