// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalAttributesDao is internal type for wrapping internal DAO implements.
type internalAttributesDao = *internal.AttributesDao

// attributesDao is the data access object for table sp_attributes.
// You can define custom methods on it to extend its functionality as you wish.
type attributesDao struct {
	internalAttributesDao
}

var (
	// Attributes is globally public accessible object for table sp_attributes operations.
	Attributes = attributesDao{
		internal.NewAttributesDao(),
	}
)

// Fill with you ideas below.
