// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalAttributeValuesDao is internal type for wrapping internal DAO implements.
type internalAttributeValuesDao = *internal.AttributeValuesDao

// attributeValuesDao is the data access object for table sp_attribute_values.
// You can define custom methods on it to extend its functionality as you wish.
type attributeValuesDao struct {
	internalAttributeValuesDao
}

var (
	// AttributeValues is globally public accessible object for table sp_attribute_values operations.
	AttributeValues = attributeValuesDao{
		internal.NewAttributeValuesDao(),
	}
)

// Fill with you ideas below.
