// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalBrandsDao is internal type for wrapping internal DAO implements.
type internalBrandsDao = *internal.BrandsDao

// brandsDao is the data access object for table sp_brands.
// You can define custom methods on it to extend its functionality as you wish.
type brandsDao struct {
	internalBrandsDao
}

var (
	// Brands is globally public accessible object for table sp_brands operations.
	Brands = brandsDao{
		internal.NewBrandsDao(),
	}
)

// Fill with you ideas below.
