// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalCartItemsDao is internal type for wrapping internal DAO implements.
type internalCartItemsDao = *internal.CartItemsDao

// cartItemsDao is the data access object for table tx_cart_items.
// You can define custom methods on it to extend its functionality as you wish.
type cartItemsDao struct {
	internalCartItemsDao
}

var (
	// CartItems is globally public accessible object for table tx_cart_items operations.
	CartItems = cartItemsDao{
		internal.NewCartItemsDao(),
	}
)

// Fill with you ideas below.
