// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalCartsDao is internal type for wrapping internal DAO implements.
type internalCartsDao = *internal.CartsDao

// cartsDao is the data access object for table tx_carts.
// You can define custom methods on it to extend its functionality as you wish.
type cartsDao struct {
	internalCartsDao
}

var (
	// Carts is globally public accessible object for table tx_carts operations.
	Carts = cartsDao{
		internal.NewCartsDao(),
	}
)

// Fill with you ideas below.
