// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalCategoryBrandsDao is internal type for wrapping internal DAO implements.
type internalCategoryBrandsDao = *internal.CategoryBrandsDao

// categoryBrandsDao is the data access object for table sp_category_brands.
// You can define custom methods on it to extend its functionality as you wish.
type categoryBrandsDao struct {
	internalCategoryBrandsDao
}

var (
	// CategoryBrands is globally public accessible object for table sp_category_brands operations.
	CategoryBrands = categoryBrandsDao{
		internal.NewCategoryBrandsDao(),
	}
)

// Fill with you ideas below.
