// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalDeliveriesDao is internal type for wrapping internal DAO implements.
type internalDeliveriesDao = *internal.DeliveriesDao

// deliveriesDao is the data access object for table tx_deliveries.
// You can define custom methods on it to extend its functionality as you wish.
type deliveriesDao struct {
	internalDeliveriesDao
}

var (
	// Deliveries is globally public accessible object for table tx_deliveries operations.
	Deliveries = deliveriesDao{
		internal.NewDeliveriesDao(),
	}
)

// Fill with you ideas below.
