// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalDeliveryTracesDao is internal type for wrapping internal DAO implements.
type internalDeliveryTracesDao = *internal.DeliveryTracesDao

// deliveryTracesDao is the data access object for table tx_delivery_traces.
// You can define custom methods on it to extend its functionality as you wish.
type deliveryTracesDao struct {
	internalDeliveryTracesDao
}

var (
	// DeliveryTraces is globally public accessible object for table tx_delivery_traces operations.
	DeliveryTraces = deliveryTracesDao{
		internal.NewDeliveryTracesDao(),
	}
)

// Fill with you ideas below.
