// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalDepartmentsDao is internal type for wrapping internal DAO implements.
type internalDepartmentsDao = *internal.DepartmentsDao

// departmentsDao is the data access object for table sys_departments.
// You can define custom methods on it to extend its functionality as you wish.
type departmentsDao struct {
	internalDepartmentsDao
}

var (
	// Departments is globally public accessible object for table sys_departments operations.
	Departments = departmentsDao{
		internal.NewDepartmentsDao(),
	}
)

// Fill with you ideas below.
