// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalInfosDao is internal type for wrapping internal DAO implements.
type internalInfosDao = *internal.InfosDao

// infosDao is the data access object for table usr_infos.
// You can define custom methods on it to extend its functionality as you wish.
type infosDao struct {
	internalInfosDao
}

var (
	// Infos is globally public accessible object for table usr_infos operations.
	Infos = infosDao{
		internal.NewInfosDao(),
	}
)

// Fill with you ideas below.
