// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalInventoriesDao is internal type for wrapping internal DAO implements.
type internalInventoriesDao = *internal.InventoriesDao

// inventoriesDao is the data access object for table sp_inventories.
// You can define custom methods on it to extend its functionality as you wish.
type inventoriesDao struct {
	internalInventoriesDao
}

var (
	// Inventories is globally public accessible object for table sp_inventories operations.
	Inventories = inventoriesDao{
		internal.NewInventoriesDao(),
	}
)

// Fill with you ideas below.
