// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalInventoryLogsDao is internal type for wrapping internal DAO implements.
type internalInventoryLogsDao = *internal.InventoryLogsDao

// inventoryLogsDao is the data access object for table sp_inventory_logs.
// You can define custom methods on it to extend its functionality as you wish.
type inventoryLogsDao struct {
	internalInventoryLogsDao
}

var (
	// InventoryLogs is globally public accessible object for table sp_inventory_logs operations.
	InventoryLogs = inventoryLogsDao{
		internal.NewInventoryLogsDao(),
	}
)

// Fill with you ideas below.
