// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalLevelsDao is internal type for wrapping internal DAO implements.
type internalLevelsDao = *internal.LevelsDao

// levelsDao is the data access object for table usr_levels.
// You can define custom methods on it to extend its functionality as you wish.
type levelsDao struct {
	internalLevelsDao
}

var (
	// Levels is globally public accessible object for table usr_levels operations.
	Levels = levelsDao{
		internal.NewLevelsDao(),
	}
)

// Fill with you ideas below.
