// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalLevelRulesDao is internal type for wrapping internal DAO implements.
type internalLevelRulesDao = *internal.LevelRulesDao

// levelRulesDao is the data access object for table usr_level_rules.
// You can define custom methods on it to extend its functionality as you wish.
type levelRulesDao struct {
	internalLevelRulesDao
}

var (
	// LevelRules is globally public accessible object for table usr_level_rules operations.
	LevelRules = levelRulesDao{
		internal.NewLevelRulesDao(),
	}
)

// Fill with you ideas below.
