// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalLoginHistoriesDao is internal type for wrapping internal DAO implements.
type internalLoginHistoriesDao = *internal.LoginHistoriesDao

// loginHistoriesDao is the data access object for table usr_login_histories.
// You can define custom methods on it to extend its functionality as you wish.
type loginHistoriesDao struct {
	internalLoginHistoriesDao
}

var (
	// LoginHistories is globally public accessible object for table usr_login_histories operations.
	LoginHistories = loginHistoriesDao{
		internal.NewLoginHistoriesDao(),
	}
)

// Fill with you ideas below.
