// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalMerchantsDao is internal type for wrapping internal DAO implements.
type internalMerchantsDao = *internal.MerchantsDao

// merchantsDao is the data access object for table mch_merchants.
// You can define custom methods on it to extend its functionality as you wish.
type merchantsDao struct {
	internalMerchantsDao
}

var (
	// Merchants is globally public accessible object for table mch_merchants operations.
	Merchants = merchantsDao{
		internal.NewMerchantsDao(),
	}
)

// Fill with you ideas below.
