// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalMerchantBankAccountsDao is internal type for wrapping internal DAO implements.
type internalMerchantBankAccountsDao = *internal.MerchantBankAccountsDao

// merchantBankAccountsDao is the data access object for table mch_merchant_bank_accounts.
// You can define custom methods on it to extend its functionality as you wish.
type merchantBankAccountsDao struct {
	internalMerchantBankAccountsDao
}

var (
	// MerchantBankAccounts is globally public accessible object for table mch_merchant_bank_accounts operations.
	MerchantBankAccounts = merchantBankAccountsDao{
		internal.NewMerchantBankAccountsDao(),
	}
)

// Fill with you ideas below.
