// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalMerchantSettlementLogsDao is internal type for wrapping internal DAO implements.
type internalMerchantSettlementLogsDao = *internal.MerchantSettlementLogsDao

// merchantSettlementLogsDao is the data access object for table mch_merchant_settlement_logs.
// You can define custom methods on it to extend its functionality as you wish.
type merchantSettlementLogsDao struct {
	internalMerchantSettlementLogsDao
}

var (
	// MerchantSettlementLogs is globally public accessible object for table mch_merchant_settlement_logs operations.
	MerchantSettlementLogs = merchantSettlementLogsDao{
		internal.NewMerchantSettlementLogsDao(),
	}
)

// Fill with you ideas below.
