// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalMerchantUsersDao is internal type for wrapping internal DAO implements.
type internalMerchantUsersDao = *internal.MerchantUsersDao

// merchantUsersDao is the data access object for table mch_merchant_users.
// You can define custom methods on it to extend its functionality as you wish.
type merchantUsersDao struct {
	internalMerchantUsersDao
}

var (
	// MerchantUsers is globally public accessible object for table mch_merchant_users operations.
	MerchantUsers = merchantUsersDao{
		internal.NewMerchantUsersDao(),
	}
)

// Fill with you ideas below.
