// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalMerchantContactsDao is internal type for wrapping internal DAO implements.
type internalMerchantContactsDao = *internal.MerchantContactsDao

// merchantContactsDao is the data access object for table mch_merchant_contacts.
// You can define custom methods on it to extend its functionality as you wish.
type merchantContactsDao struct {
	internalMerchantContactsDao
}

var (
	// MerchantContacts is globally public accessible object for table mch_merchant_contacts operations.
	MerchantContacts = merchantContactsDao{
		internal.NewMerchantContactsDao(),
	}
)

// Fill with you ideas below.
