// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalMerchantBalancesDao is internal type for wrapping internal DAO implements.
type internalMerchantBalancesDao = *internal.MerchantBalancesDao

// merchantBalancesDao is the data access object for table mch_merchant_balances.
// You can define custom methods on it to extend its functionality as you wish.
type merchantBalancesDao struct {
	internalMerchantBalancesDao
}

var (
	// MerchantBalances is globally public accessible object for table mch_merchant_balances operations.
	MerchantBalances = merchantBalancesDao{
		internal.NewMerchantBalancesDao(),
	}
)

// Fill with you ideas below.
