// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalMerchantRolesDao is internal type for wrapping internal DAO implements.
type internalMerchantRolesDao = *internal.MerchantRolesDao

// merchantRolesDao is the data access object for table mch_merchant_roles.
// You can define custom methods on it to extend its functionality as you wish.
type merchantRolesDao struct {
	internalMerchantRolesDao
}

var (
	// MerchantRoles is globally public accessible object for table mch_merchant_roles operations.
	MerchantRoles = merchantRolesDao{
		internal.NewMerchantRolesDao(),
	}
)

// Fill with you ideas below.
