// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalMerchantRolePermissionsDao is internal type for wrapping internal DAO implements.
type internalMerchantRolePermissionsDao = *internal.MerchantRolePermissionsDao

// merchantRolePermissionsDao is the data access object for table mch_merchant_role_permissions.
// You can define custom methods on it to extend its functionality as you wish.
type merchantRolePermissionsDao struct {
	internalMerchantRolePermissionsDao
}

var (
	// MerchantRolePermissions is globally public accessible object for table mch_merchant_role_permissions operations.
	MerchantRolePermissions = merchantRolePermissionsDao{
		internal.NewMerchantRolePermissionsDao(),
	}
)

// Fill with you ideas below.
