// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalMerchantQualificationsDao is internal type for wrapping internal DAO implements.
type internalMerchantQualificationsDao = *internal.MerchantQualificationsDao

// merchantQualificationsDao is the data access object for table mch_merchant_qualifications.
// You can define custom methods on it to extend its functionality as you wish.
type merchantQualificationsDao struct {
	internalMerchantQualificationsDao
}

var (
	// MerchantQualifications is globally public accessible object for table mch_merchant_qualifications operations.
	MerchantQualifications = merchantQualificationsDao{
		internal.NewMerchantQualificationsDao(),
	}
)

// Fill with you ideas below.
