// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalNotificationsDao is internal type for wrapping internal DAO implements.
type internalNotificationsDao = *internal.NotificationsDao

// notificationsDao is the data access object for table base_notifications.
// You can define custom methods on it to extend its functionality as you wish.
type notificationsDao struct {
	internalNotificationsDao
}

var (
	// Notifications is globally public accessible object for table base_notifications operations.
	Notifications = notificationsDao{
		internal.NewNotificationsDao(),
	}
)

// Fill with you ideas below.
