// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalNotificationReadsDao is internal type for wrapping internal DAO implements.
type internalNotificationReadsDao = *internal.NotificationReadsDao

// notificationReadsDao is the data access object for table base_notification_reads.
// You can define custom methods on it to extend its functionality as you wish.
type notificationReadsDao struct {
	internalNotificationReadsDao
}

var (
	// NotificationReads is globally public accessible object for table base_notification_reads operations.
	NotificationReads = notificationReadsDao{
		internal.NewNotificationReadsDao(),
	}
)

// Fill with you ideas below.
