// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalNotificationTemplatesDao is internal type for wrapping internal DAO implements.
type internalNotificationTemplatesDao = *internal.NotificationTemplatesDao

// notificationTemplatesDao is the data access object for table base_notification_templates.
// You can define custom methods on it to extend its functionality as you wish.
type notificationTemplatesDao struct {
	internalNotificationTemplatesDao
}

var (
	// NotificationTemplates is globally public accessible object for table base_notification_templates operations.
	NotificationTemplates = notificationTemplatesDao{
		internal.NewNotificationTemplatesDao(),
	}
)

// Fill with you ideas below.
