// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalOperationLogsDao is internal type for wrapping internal DAO implements.
type internalOperationLogsDao = *internal.OperationLogsDao

// operationLogsDao is the data access object for table sys_operation_logs.
// You can define custom methods on it to extend its functionality as you wish.
type operationLogsDao struct {
	internalOperationLogsDao
}

var (
	// OperationLogs is globally public accessible object for table sys_operation_logs operations.
	OperationLogs = operationLogsDao{
		internal.NewOperationLogsDao(),
	}
)

// Fill with you ideas below.
