// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalOrderItemsDao is internal type for wrapping internal DAO implements.
type internalOrderItemsDao = *internal.OrderItemsDao

// orderItemsDao is the data access object for table tx_order_items.
// You can define custom methods on it to extend its functionality as you wish.
type orderItemsDao struct {
	internalOrderItemsDao
}

var (
	// OrderItems is globally public accessible object for table tx_order_items operations.
	OrderItems = orderItemsDao{
		internal.NewOrderItemsDao(),
	}
)

// Fill with you ideas below.