// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalOrdersDao is internal type for wrapping internal DAO implements.
type internalOrdersDao = *internal.OrdersDao

// ordersDao is the data access object for table tx_order.
// You can define custom methods on it to extend its functionality as you wish.
type ordersDao struct {
	internalOrdersDao
}

var (
	// Orders is globally public accessible object for table tx_order operations.
	Orders = ordersDao{
		internal.NewOrdersDao(),
	}
)

// Fill with you ideas below.