// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalOrderLogsDao is internal type for wrapping internal DAO implements.
type internalOrderLogsDao = *internal.OrderLogsDao

// orderLogsDao is the data access object for table tx_order_logs.
// You can define custom methods on it to extend its functionality as you wish.
type orderLogsDao struct {
	internalOrderLogsDao
}

var (
	// OrderLogs is globally public accessible object for table tx_order_logs operations.
	OrderLogs = orderLogsDao{
		internal.NewOrderLogsDao(),
	}
)

// Fill with you ideas below.