// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalPaymentLogsDao is internal type for wrapping internal DAO implements.
type internalPaymentLogsDao = *internal.PaymentLogsDao

// paymentLogsDao is the data access object for table tx_payment_log.
// You can define custom methods on it to extend its functionality as you wish.
type paymentLogsDao struct {
	internalPaymentLogsDao
}

var (
	// PaymentLogs is globally public accessible object for table tx_payment_log operations.
	PaymentLogs = paymentLogsDao{
		internal.NewPaymentLogsDao(),
	}
)

// Fill with you ideas below.