// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalPaymentsDao is internal type for wrapping internal DAO implements.
type internalPaymentsDao = *internal.PaymentsDao

// paymentsDao is the data access object for table tx_payments.
// You can define custom methods on it to extend its functionality as you wish.
type paymentsDao struct {
	internalPaymentsDao
}

var (
	// Payments is globally public accessible object for table tx_payments operations.
	Payments = paymentsDao{
		internal.NewPaymentsDao(),
	}
)

// Fill with you ideas below.