// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalPermissionsDao is internal type for wrapping internal DAO implements.
type internalPermissionsDao = *internal.PermissionsDao

// permissionsDao is the data access object for table sys_permissions.
// You can define custom methods on it to extend its functionality as you wish.
type permissionsDao struct {
	internalPermissionsDao
}

var (
	// Permissions is globally public accessible object for table sys_permissions operations.
	Permissions = permissionsDao{
		internal.NewPermissionsDao(),
	}
)

// Fill with you ideas below.
