// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalPointsRulesDao is internal type for wrapping internal DAO implements.
type internalPointsRulesDao = *internal.PointsRulesDao

// pointsRulesDao is the data access object for table usr_points_rules.
// You can define custom methods on it to extend its functionality as you wish.
type pointsRulesDao struct {
	internalPointsRulesDao
}

var (
	// PointsRules is globally public accessible object for table usr_points_rules operations.
	PointsRules = pointsRulesDao{
		internal.NewPointsRulesDao(),
	}
)

// Fill with you ideas below.
