// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalPointsDao is internal type for wrapping internal DAO implements.
type internalPointsDao = *internal.PointsDao

// pointsDao is the data access object for table usr_points.
// You can define custom methods on it to extend its functionality as you wish.
type pointsDao struct {
	internalPointsDao
}

var (
	// Points is globally public accessible object for table usr_points operations.
	Points = pointsDao{
		internal.NewPointsDao(),
	}
)

// Fill with you ideas below.
