// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalProductAttributesDao is internal type for wrapping internal DAO implements.
type internalProductAttributesDao = *internal.ProductAttributesDao

// productAttributesDao is the data access object for table sp_product_attributes.
// You can define custom methods on it to extend its functionality as you wish.
type productAttributesDao struct {
	internalProductAttributesDao
}

var (
	// ProductAttributes is globally public accessible object for table sp_product_attributes operations.
	ProductAttributes = productAttributesDao{
		internal.NewProductAttributesDao(),
	}
)

// Fill with you ideas below.
