// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalProductVersionsDao is internal type for wrapping internal DAO implements.
type internalProductVersionsDao = *internal.ProductVersionsDao

// productVersionsDao is the data access object for table sp_product_versions.
// You can define custom methods on it to extend its functionality as you wish.
type productVersionsDao struct {
	internalProductVersionsDao
}

var (
	// ProductVersions is globally public accessible object for table sp_product_versions operations.
	ProductVersions = productVersionsDao{
		internal.NewProductVersionsDao(),
	}
)

// Fill with you ideas below.
