// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalProductDescriptionsDao is internal type for wrapping internal DAO implements.
type internalProductDescriptionsDao = *internal.ProductDescriptionsDao

// productDescriptionsDao is the data access object for table sp_product_descriptions.
// You can define custom methods on it to extend its functionality as you wish.
type productDescriptionsDao struct {
	internalProductDescriptionsDao
}

var (
	// ProductDescriptions is globally public accessible object for table sp_product_descriptions operations.
	ProductDescriptions = productDescriptionsDao{
		internal.NewProductDescriptionsDao(),
	}
)

// Fill with you ideas below.
