// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalPromotionRulesDao is internal type for wrapping internal DAO implements.
type internalPromotionRulesDao = *internal.PromotionRulesDao

// promotionRulesDao is the data access object for table mkt_promotion_rules.
// You can define custom methods on it to extend its functionality as you wish.
type promotionRulesDao struct {
	internalPromotionRulesDao
}

var (
	// PromotionRules is globally public accessible object for table mkt_promotion_rules operations.
	PromotionRules = promotionRulesDao{
		internal.NewPromotionRulesDao(),
	}
)

// Fill with you ideas below.
