// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalPromotionUsageLogsDao is internal type for wrapping internal DAO implements.
type internalPromotionUsageLogsDao = *internal.PromotionUsageLogsDao

// promotionUsageLogsDao is the data access object for table mkt_promotion_usage_logs.
// You can define custom methods on it to extend its functionality as you wish.
type promotionUsageLogsDao struct {
	internalPromotionUsageLogsDao
}

var (
	// PromotionUsageLogs is globally public accessible object for table mkt_promotion_usage_logs operations.
	PromotionUsageLogs = promotionUsageLogsDao{
		internal.NewPromotionUsageLogsDao(),
	}
)

// Fill with you ideas below.
