// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalPromotionProductsDao is internal type for wrapping internal DAO implements.
type internalPromotionProductsDao = *internal.PromotionProductsDao

// promotionProductsDao is the data access object for table mkt_promotion_products.
// You can define custom methods on it to extend its functionality as you wish.
type promotionProductsDao struct {
	internalPromotionProductsDao
}

var (
	// PromotionProducts is globally public accessible object for table mkt_promotion_products operations.
	PromotionProducts = promotionProductsDao{
		internal.NewPromotionProductsDao(),
	}
)

// Fill with you ideas below.
