// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalPromotionStocksDao is internal type for wrapping internal DAO implements.
type internalPromotionStocksDao = *internal.PromotionStocksDao

// promotionStocksDao is the data access object for table mkt_promotion_stocks.
// You can define custom methods on it to extend its functionality as you wish.
type promotionStocksDao struct {
	internalPromotionStocksDao
}

var (
	// PromotionStocks is globally public accessible object for table mkt_promotion_stocks operations.
	PromotionStocks = promotionStocksDao{
		internal.NewPromotionStocksDao(),
	}
)

// Fill with you ideas below.
