// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalPromotionsDao is internal type for wrapping internal DAO implements.
type internalPromotionsDao = *internal.PromotionsDao

// promotionsDao is the data access object for table mkt_promotions.
// You can define custom methods on it to extend its functionality as you wish.
type promotionsDao struct {
	internalPromotionsDao
}

var (
	// Promotions is globally public accessible object for table mkt_promotions operations.
	Promotions = promotionsDao{
		internal.NewPromotionsDao(),
	}
)

// Fill with you ideas below.
