// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalRefundsDao is internal type for wrapping internal DAO implements.
type internalRefundsDao = *internal.RefundsDao

// refundsDao is the data access object for table tx_refunds.
// You can define custom methods on it to extend its functionality as you wish.
type refundsDao struct {
	internalRefundsDao
}

var (
	// Refunds is globally public accessible object for table tx_refunds operations.
	Refunds = refundsDao{
		internal.NewRefundsDao(),
	}
)

// Fill with you ideas below.