// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalReviewAuditLogsDao is internal type for wrapping internal DAO implements.
type internalReviewAuditLogsDao = *internal.ReviewAuditLogsDao

// reviewAuditLogsDao is the data access object for table rev_review_audit_logs.
// You can define custom methods on it to extend its functionality as you wish.
type reviewAuditLogsDao struct {
	internalReviewAuditLogsDao
}

var (
	// ReviewAuditLogs is globally public accessible object for table rev_review_audit_logs operations.
	ReviewAuditLogs = reviewAuditLogsDao{
		internal.NewReviewAuditLogsDao(),
	}
)

// Fill with you ideas below.
