// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalReviewStatisticsDao is internal type for wrapping internal DAO implements.
type internalReviewStatisticsDao = *internal.ReviewStatisticsDao

// reviewStatisticsDao is the data access object for table rev_review_statistics.
// You can define custom methods on it to extend its functionality as you wish.
type reviewStatisticsDao struct {
	internalReviewStatisticsDao
}

var (
	// ReviewStatistics is globally public accessible object for table rev_review_statistics operations.
	ReviewStatistics = reviewStatisticsDao{
		internal.NewReviewStatisticsDao(),
	}
)

// Fill with you ideas below.
