// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalReviewsDao is internal type for wrapping internal DAO implements.
type internalReviewsDao = *internal.ReviewsDao

// reviewsDao is the data access object for table rev_reviews.
// You can define custom methods on it to extend its functionality as you wish.
type reviewsDao struct {
	internalReviewsDao
}

var (
	// Reviews is globally public accessible object for table rev_reviews operations.
	Reviews = reviewsDao{
		internal.NewReviewsDao(),
	}
)

// Fill with you ideas below.
