// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalReviewMediaDao is internal type for wrapping internal DAO implements.
type internalReviewMediaDao = *internal.ReviewMediaDao

// reviewMediaDao is the data access object for table rev_review_media.
// You can define custom methods on it to extend its functionality as you wish.
type reviewMediaDao struct {
	internalReviewMediaDao
}

var (
	// ReviewMedia is globally public accessible object for table rev_review_media operations.
	ReviewMedia = reviewMediaDao{
		internal.NewReviewMediaDao(),
	}
)

// Fill with you ideas below.
