// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalReviewRepliesDao is internal type for wrapping internal DAO implements.
type internalReviewRepliesDao = *internal.ReviewRepliesDao

// reviewRepliesDao is the data access object for table rev_review_replies.
// You can define custom methods on it to extend its functionality as you wish.
type reviewRepliesDao struct {
	internalReviewRepliesDao
}

var (
	// ReviewReplies is globally public accessible object for table rev_review_replies operations.
	ReviewReplies = reviewRepliesDao{
		internal.NewReviewRepliesDao(),
	}
)

// Fill with you ideas below.
