// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalReviewUsefulnessDao is internal type for wrapping internal DAO implements.
type internalReviewUsefulnessDao = *internal.ReviewUsefulnessDao

// reviewUsefulnessDao is the data access object for table rev_review_usefulness.
// You can define custom methods on it to extend its functionality as you wish.
type reviewUsefulnessDao struct {
	internalReviewUsefulnessDao
}

var (
	// ReviewUsefulness is globally public accessible object for table rev_review_usefulness operations.
	ReviewUsefulness = reviewUsefulnessDao{
		internal.NewReviewUsefulnessDao(),
	}
)

// Fill with you ideas below.
