// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalRolePermissionsDao is internal type for wrapping internal DAO implements.
type internalRolePermissionsDao = *internal.RolePermissionsDao

// rolePermissionsDao is the data access object for table sys_role_permissions.
// You can define custom methods on it to extend its functionality as you wish.
type rolePermissionsDao struct {
	internalRolePermissionsDao
}

var (
	// RolePermissions is globally public accessible object for table sys_role_permissions operations.
	RolePermissions = rolePermissionsDao{
		internal.NewRolePermissionsDao(),
	}
)

// Fill with you ideas below.
