// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalSettlementDetailsDao is internal type for wrapping internal DAO implements.
type internalSettlementDetailsDao = *internal.SettlementDetailsDao

// settlementDetailsDao is the data access object for table mch_settlement_details.
// You can define custom methods on it to extend its functionality as you wish.
type settlementDetailsDao struct {
	internalSettlementDetailsDao
}

var (
	// SettlementDetails is globally public accessible object for table mch_settlement_details operations.
	SettlementDetails = settlementDetailsDao{
		internal.NewSettlementDetailsDao(),
	}
)

// Fill with you ideas below.
