// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalSkuSpecsDao is internal type for wrapping internal DAO implements.
type internalSkuSpecsDao = *internal.SkuSpecsDao

// skuSpecsDao is the data access object for table sp_sku_specs.
// You can define custom methods on it to extend its functionality as you wish.
type skuSpecsDao struct {
	internalSkuSpecsDao
}

var (
	// SkuSpecs is globally public accessible object for table sp_sku_specs operations.
	SkuSpecs = skuSpecsDao{
		internal.NewSkuSpecsDao(),
	}
)

// Fill with you ideas below.
