// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalSkusDao is internal type for wrapping internal DAO implements.
type internalSkusDao = *internal.SkusDao

// skusDao is the data access object for table sp_skus.
// You can define custom methods on it to extend its functionality as you wish.
type skusDao struct {
	internalSkusDao
}

var (
	// Skus is globally public accessible object for table sp_skus operations.
	Skus = skusDao{
		internal.NewSkusDao(),
	}
)

// Fill with you ideas below.
