// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalStaffRolesDao is internal type for wrapping internal DAO implements.
type internalStaffRolesDao = *internal.StaffRolesDao

// staffRolesDao is the data access object for table sys_staff_roles.
// You can define custom methods on it to extend its functionality as you wish.
type staffRolesDao struct {
	internalStaffRolesDao
}

var (
	// StaffRoles is globally public accessible object for table sys_staff_roles operations.
	StaffRoles = staffRolesDao{
		internal.NewStaffRolesDao(),
	}
)

// Fill with you ideas below.
