// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalSubOrdersDao is internal type for wrapping internal DAO implements.
type internalSubOrdersDao = *internal.SubOrdersDao

// subOrdersDao is the data access object for table tx_sub_orders.
// You can define custom methods on it to extend its functionality as you wish.
type subOrdersDao struct {
	internalSubOrdersDao
}

var (
	// SubOrders is globally public accessible object for table tx_sub_orders operations.
	SubOrders = subOrdersDao{
		internal.NewSubOrdersDao(),
	}
)

// Fill with you ideas below.