// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalSysLoginHistoriesDao is internal type for wrapping internal DAO implements.
type internalSysLoginHistoriesDao = *internal.SysLoginHistoriesDao

// sysLoginHistoriesDao is the data access object for table sys_login_histories.
// You can define custom methods on it to extend its functionality as you wish.
type sysLoginHistoriesDao struct {
	internalSysLoginHistoriesDao
}

var (
	// SysLoginHistories is globally public accessible object for table sys_login_histories operations.
	SysLoginHistories = sysLoginHistoriesDao{
		internal.NewSysLoginHistoriesDao(),
	}
)

// Fill with you ideas below.
