// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalUserPromotionsDao is internal type for wrapping internal DAO implements.
type internalUserPromotionsDao = *internal.UserPromotionsDao

// userPromotionsDao is the data access object for table mkt_user_promotions.
// You can define custom methods on it to extend its functionality as you wish.
type userPromotionsDao struct {
	internalUserPromotionsDao
}

var (
	// UserPromotions is globally public accessible object for table mkt_user_promotions operations.
	UserPromotions = userPromotionsDao{
		internal.NewUserPromotionsDao(),
	}
)

// Fill with you ideas below.
