// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalUsrLoginHistoriesDao is internal type for wrapping internal DAO implements.
type internalUsrLoginHistoriesDao = *internal.UsrLoginHistoriesDao

// usrLoginHistoriesDao is the data access object for table usr_login_histories.
// You can define custom methods on it to extend its functionality as you wish.
type usrLoginHistoriesDao struct {
	internalUsrLoginHistoriesDao
}

var (
	// UsrLoginHistories is globally public accessible object for table usr_login_histories operations.
	UsrLoginHistories = usrLoginHistoriesDao{
		internal.NewUsrLoginHistoriesDao(),
	}
)

// Fill with you ideas below.
