// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/internal/dao/internal"
)

// internalWarehousesDao is internal type for wrapping internal DAO implements.
type internalWarehousesDao = *internal.WarehousesDao

// warehousesDao is the data access object for table sp_warehouses.
// You can define custom methods on it to extend its functionality as you wish.
type warehousesDao struct {
	internalWarehousesDao
}

var (
	// Warehouses is globally public accessible object for table sp_warehouses operations.
	Warehouses = warehousesDao{
		internal.NewWarehousesDao(),
	}
)

// Fill with you ideas below.
